### ISSUE TITLE
Enhancement: Improve User Experience for React based Applications

### ISSUE THREAD

**Issue by evenstensberg** [guess-js/guess#129]
As React is a fairly popular framework it would be awesome to have the initial user experience with GuessJS better. In practise, this would mean that a Router configuration file (which is either js or jsx) is read as static routes for Guess JS to parse. Either that or a json-like configuration that the user could specify in their app. Refering to conversation at JSConfEU to improve the impression of using the framework as a whole. 

In addition, a method to run static apps once and generating a list over routes used would be great so that to programatic interface is needed to run GuessJS.

**Comment by mgechev** [comment]
To statically figure out the dynamic routes and associate the individual paths with chunk entry points might be a bit tricky in the general case. The conventions you're suggesting make sense.

@mjackson & @addyosmani may also have thoughts on this.

**Comment by addyosmani** [comment]
I love the idea of a convention-based approach to better supporting React apps. I would like to see if we can achieve this without introducing our own arbitrary routes configuration format (ideally this can be inferred).

I also think we should start with better support for "production" scaffolds like Next.js. I'm curious how often sites use projects like https://github.com/fridays/next-routes.

**Comment by evenstensberg** [comment]
This is probably a job for the open frameworks team then, right?

**Comment by mgechev** [comment]
Any further actions we're taking here?

Something I imagine is:

1. ESLint rule which validates that route definitions are statically analyzable by Guess.js
2. Alignment of the Guess.js react parser with the most user ergonomic route definition syntax

From here, everything should work out of the box. We already have good support for Next.js. A step forward there would be to implement the ahead-of-time predictive strategy we have for Angular.

**Comment by mgechev** [comment]
Seems like the DX for folks using meta frameworks (Next.js & Gatsby) could be improved. With @wardpeet we're having a discussion how to introduce the ahead-of-time prefetching model in Gatsby.

I'll close this discussion for now since it doesn't seem possible to make this work in the general case.

**Comment by evenstensberg** [comment]
Is there a way to not only have this in meta-frameworks but React itself?

**Comment by wardpeet** [comment]
Hey, sorry for the late answer. I still have to get to the bottom of this for Gatsby.

@evenstensberg I think it's going to be pretty difficult to improve DX for none meta frameworks as you'll need to know what pages are created, which components they load, ...

**Comment by evenstensberg** [comment]
Yeah, indeed. I was hoping we'd find a place where we could parse a routing file and use that for guess-ing
