### ISSUE TITLE
[guess-webpack] API - in production mode guess function not defined

### ISSUE THREAD

**Issue by pixelmord** [guess-js/guess#139]
I used the nextJS demo as a base for my project (https://github.com/mgechev/guess-next).
When I run the nextJS server with NODE_ENV=production then the `guess()` function is not attached to the window object.

**Comment by pixelmord** [comment]
In the JS component:
```
import { guess } from 'guess-webpack/api';
if (typeof window !== 'undefined') {
    predictions = Object.keys(guess()).sort((a, b) => a.length - b.length);
    predictions.forEach(p => router.prefetch(p));
  }
```

Versions:

`guess-webpack@0.3.7 `, `next@8.1.0`

**Comment by mgechev** [comment]
Thanks for reporting this out! I'll look at the issue in the next a couple of days.

**Comment by mgechev** [comment]
@pixelmord I updated the dependencies in the demo. Everything seem to be working for me. Would you verify your webpack configuration looks like:

```js
const { GuessPlugin } = require('guess-webpack');

module.exports = {
  webpack: function(config, { isServer }) {
    if (isServer) return config;
    config.plugins.push(
      new GuessPlugin({
        debug: true,
        reportProvider() {
          return Promise.resolve(JSON.parse(require('fs').readFileSync('./routes.json')));
        },
        runtime: {
          delegate: true
        }
      })
    );
    return config;
  }
};
```

**Comment by mgechev** [comment]
Closing it due to inactivity.
