### ISSUE TITLE
[question] In which way is ML / AI used for guess' predictions ?

### ISSUE THREAD

**Issue by pixelmord** [guess-js/guess#140]
I am trying to get a better understanding of the features of guess.
At what point on an implementation level is ML used? Is the GA page transition data used as an input for the model application? Does the ML happen on the server and is done on the Google Analytics layer or is it run in the client (after retrieving data from GA?) ?

Thank you very much for pointing me in the right direction

**Comment by mgechev** [comment]
You can review the information in the readme or my original [blog](https://blog.mgechev.com/2018/03/18/machine-learning-data-driven-bundling-webpack-javascript-markov-chain-angular-react/) [posts](https://blog.mgechev.com/2018/05/09/introducing-guess-js-data-driven-user-experiences-web/) for further details.
