### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [guess-js/guess#197]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by mgechev** [comment]
There are apps for the e2e tests that depend on this package, which should be fine. Thanks for the heads up!
