### ISSUE TITLE
[guess-parser] v0.4.x has no type definition files

### ISSUE THREAD

**Issue by chrisguttandin** [guess-js/guess#214]
I'm not sure if version 0.4.x is meant to be used already because I can't find it here in any of the branches. However it is available on npm but I noticed that it is missing the type definition files. 

Here is the diff from [Package Diff](https://diff.intrinsic.com) which shows what has changed.

https://diff.intrinsic.com/guess-parser/0.3.13/0.4.2

Please let me know if there is anything I can do to help you out.

**Comment by mgechev** [comment]
Version 0.4.x is based on [this](https://github.com/guess-js/guess/pull/210) PR. I'll publish type definitions sometime soon. There are few more regressions I need to fix, but by the end of today/tomorrow this should be all working.

**Comment by chrisguttandin** [comment]
Thanks for letting me know. I don't mind if it won't be ready by tomorrow. I just thought you might be unaware of the regression.

**Comment by mgechev** [comment]
Everything should be fine now. The improvement that 0.4.x introduced is around handling cyclic dependencies.

`guess-parser` still doesn't have support for TypeScript path mapping, but so far this feature hasn't been widely requested.

**Comment by chrisguttandin** [comment]
Thank you very much.
