### ISSUE TITLE
Allow other providers than Google Analytics

### ISSUE THREAD

**Issue by muuvmuuv** [guess-js/guess#233]
Hey, I really like the idea of Guess and this IS the future of how people browse websites faster with less network actions BUT I'm really not a fan of GA and does not use it so this is a downside.

I haven't looked closer into the codebase yet but might it be possible to extend Guess with plugins to use other providers than GA? I'm using [SimpleAnalytics](https://simpleanalytics.com/) which is a user-friendly and cleaner alternative to GA. They also provide an [API here](https://docs.simpleanalytics.com/api).

I'm looking forward what you think.

**Comment by mgechev** [comment]
Hey, thank you for the interest! Guess.js supports an arbitrary report provider.

As part of the GuessPlugin config you should specify an async function called `reportProvider` which returns an object in the following format:

```js
{
  "/": {
    "/about": 88 // number of visits from / to /about
    "/home": 12 // number or visits from / to /home
  },
  "/home": {
    "/": 90,
  }
  // etc.
}
```

Sorry for the lack of good documentation at this point. This is something we're currently working on.

**Comment by guanzo** [comment]
What about an arbitrary rpoert provider for guess-static-sites?
