### ISSUE TITLE
Build error on nested routes configuration

### ISSUE THREAD

**Issue by morganpizzini** [guess-js/guess#234]
Got the following error when run build with guess opt active

```
UnhandledPromiseRejectionWarning: TypeError: childrenArray.getChildren is not a function
    at getRoute (C:\Users\<MY-PATH>\node_modules\guess-parser\dist\guess-parser\index.js:364:14)
```
It occurs only when I setup nested routes configuration:
- 'administration'
  - 'second'
- ''
  - 'first'
  - ''
  - '**'

With routes at the same level:
- 'second'
- 'first'
- ''
- '**'

I don't get any error.

Repo for reproducing the error: [link](https://github.com/morganpizzini/guess-test)
Build command: `npm run build:guess`

**Comment by mgechev** [comment]
Thanks for providing a repro! I'll try to check this out next week.

**Comment by MitkoTschimev** [comment]
I can confirm this problem. I will try to dig in too.

**Comment by MitkoTschimev** [comment]
So what I figured out is that the code is calling a function on an array which not exists. I fixed it on my fork and it was working.

@mgechev Any idea why u are trying to call the function getChildren? Maybe a typescript version?

![image](https://user-images.githubusercontent.com/988473/66606062-5bedba80-ebc2-11e9-88e2-2b0641ee763b.png)

I created a condition at this point to support both. Native arrays and that one which has this function. I will create a PR ;)

**Comment by mgechev** [comment]
@morganpizzini, I released this over a week ago. Let me know if the issue is still not resolved.

**Comment by morganpizzini** [comment]
It was working, I put also an approve on the PR, thank you!
At the moment I just upgrade to 0.4.10, but I got the following error. I didn't touch anything in source code
```
 UnhandledPromiseRejectionWarning: Error: Cannot find source file for path: <my-path>/node_modules/util/util.js
    at imports (<my-path>\node_modules\guess-parser\dist\guess-parser\index.js:193:15)
```
Sould I open a new Issue?
Thank you!

**Comment by mgechev** [comment]
@morganpizzini would you provide a minimal demo where I can reproduce the problem? Please open a new issue with it. Thanks!
