### ISSUE TITLE
Detect when Module is imported as Lazy

### ISSUE THREAD

**Issue by morganpizzini** [guess-js/guess#255]
After updating to 0.4.10, during the build guess fail and prompt 
`Multiple root routing modules found` when I try to use lazy loading modules.

By looking inside the node_module library I made some test and find out that "filter never filter" at `var roots = allModulePaths.filter(function (m) { return !childModules.has(m); });` inside `index.js`.
`allModulePaths` are the **routing module path**, while `childModules` are the **module path**.

Could it depends on how the object registry is created? (index.ts:490)

Here's the [repo](https://github.com/morganpizzini/guess-test) for testing. I also included a script for run only guess `node ./guess-test.js`

**Comment by mgechev** [comment]
To workaround this just pass a second argument to `parseAngularRoutes` specifying which root modules to be ignored in an array (i.e. everything else that the parser returns except your app module).

You can use `parseAngularRoutes` the same way as `parseRoutes` but make sure you specify the `tsconfig` path as the first argument (and an array with excluded root modules as I mentioned above).

**Comment by chrisguttandin** [comment]
Hi @morganpizzini, are you by chance using a Windows machine? If so #257 might have fixed the issue.

**Comment by mgechev** [comment]
@morganpizzini did you have a chance to try the latest release?

**Comment by morganpizzini** [comment]
Just test Version 0.4.11 and I successfully reach guess's authorization page, thank you!

**Comment by mgechev** [comment]
🎉🎉🎉
