### ISSUE TITLE
Implement Google Analytics "What to prefetch?" helper

### ISSUE THREAD

**Issue by addyosmani** [guess-js/guess#3]
**Goal:** Make it trivial for developers to select a GA account and see what what the likely next pages a user would visit for any given path might be. 

**Prototype:** https://predictjs.firebaseapp.com

Next steps:

- [ ] Rewrite/clean-up code
- [ ] Add support for pre-populating all your GA accounts and Views (like on [query-explorer](https://ga-dev-tools.appspot.com/query-explorer/))
- [ ] Check it in somewhere. Either here (if Google's OSS office is okay with that, or our GitHub and I'll drop in a link)

**Comment by mgechev** [comment]
Closing this issue for now. Looks like https://predictjs.firebaseapp.com/ does descent job already; we can revisit if necessary later.
