### ISSUE TITLE
TypeError: Cannot read property 'eagerRoutes' of undefined

### ISSUE THREAD

**Issue by JandroMejia97** [guess-js/guess#311]
# Can´t read property 'eagerRoutes' of undefined

My _extend.webpack.config.js_ is like below:
```js
const { GuessPlugin } = require('guess-webpack');
const { parseRoutes } = require('guess-parser');

module.exports = {
  plugins: [
    new GuessPlugin({
      GA: '<GAV Id>', 
      runtime: {
        delegate: false
      },
      routeProvider() {
        return parseRoutes('.');
      }
    })
  ]
};

```

But I get this error when I run the `ng build --prod` command.

```node
(node:1672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'eagerRoutes' of undefined
    at collectRoutingModules (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-parser\dist\guess-parser\index.js:465:17)
    at processLazyRoute (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-parser\dist\guess-parser\index.js:463:9)
    at Array.forEach (<anonymous>)
    at collectRoutingModules (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-parser\dist\guess-parser\index.js:466:28)
    at Object.exports.parseRoutes (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-parser\dist\guess-parser\index.js:598:9)
    at exports.parseRoutes (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-parser\dist\guess-parser\index.js:843:28)
    at Object.routeProvider (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\extend.webpack.config.js:16:16)
    at extractRoutes (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-webpack\dist\guess-webpack\main.js:457:39)
    at GuessPlugin._execute (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-webpack\dist\guess-webpack\main.js:490:9)
    at C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\guess-webpack\dist\guess-webpack\main.js:486:54
    at _next0 (eval at create (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at C:\Users\aleja\OneDrive\Documents\Cursos\Angular\platzi-store\node_modules\copy-webpack-plugin\dist\index.js:91:9
(node:1672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mgechev** [comment]
@JandroMejia97 thanks for giving Guess.js a try! Looks like the parser fails to resolve the routes in your app.

Unfortunately I cannot debug the issue without a repro. Would you be able to share a minimal example where you can reproduce the problem?

**Comment by mgechev** [comment]
Just found the public repo in your account and reproduced the problem. I'll see what I can find.

**Comment by JandroMejia97** [comment]
Do you think it's good if I share the repository of the project I'm working on? So you can play it directly.

**Comment by JandroMejia97** [comment]
@mgechev make sure you are working with the performance branch, since that is where I am applying Guess.js for a performance course.

**Comment by mgechev** [comment]
Guess.js gets confused because you don't have route declarations in `about-routing.module.ts`, which makes sense, but still the failure should not happen.

Until I push a fix, you can workaround the problem by replacing your `about-routing.module.ts` with:

import { NgModule, Component } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

@Component({
  selector: 'foo',
  template: 'bar'
})
export class AboutComponent {}


const routes: Routes = [{
  path: '',
  pathMatch: 'full',
  component: AboutComponent
}];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class AboutRoutingModule { }
```

**Comment by JandroMejia97** [comment]
I will make this modification, maybe that is the problem

**Comment by mgechev** [comment]
Fixed in https://github.com/guess-js/guess/pull/312. Let me know when you verify so I can release.

**Comment by JandroMejia97** [comment]
Yes, this was the problem. Thanks for your valuable help. Issue solved.

**Comment by JandroMejia97** [comment]
@mgechev I have another question, after executing the `ng build --prod` command and this command opens a new window to try to log in to my Google account, this is not possible because Google blocks access. Attached image.
![Uploading image.png…](Google blocks access)

**Comment by mgechev** [comment]
Not sure what the text says. Would you translate?

**Comment by JandroMejia97** [comment]
Translation: Logging in with Google in this application has been temporarily disabled
We have not yet verified this application so you can use Google login.

**Comment by mgechev** [comment]
I'm not sure why Google is blocking it that aggressively. Here's what usually happens:

Step 1:

<img width="715" alt="Screen Shot 2020-01-23 at 3 29 20 PM" src="https://user-images.githubusercontent.com/455023/73032885-37c28c00-3df5-11ea-8b13-0f9a61f21fdd.png">

Step 2:

<img width="761" alt="Screen Shot 2020-01-23 at 3 29 27 PM" src="https://user-images.githubusercontent.com/455023/73032891-3f823080-3df5-11ea-9af9-49f1636e720c.png">

I'll see what I can do to verify the app.

**Comment by JandroMejia97** [comment]
In this case, doing what you recommend is not possible.

**Comment by JandroMejia97** [comment]
In the image you can see that none of these options appear

**Comment by mgechev** [comment]
Unfortunately, there's nothing I can do at this point. You can [generate JWT tokens](https://2ality.com/2015/10/google-analytics-api.html) and provide them to Guess.js in a similar way I did [here](https://github.com/mgechev/revive.run/blob/master/gatsby-config.js#L79-L82).
