### ISSUE TITLE
guess-parser incorrect listing of child routes

### ISSUE THREAD

**Issue by SanderElias** [guess-js/guess#313]
I created a small [demo app](https://github.com/SanderElias/sampleToShowGuessIssue/invitations) to showcase this issue.

The route configuration that gets parsed incorrectly:
```ts
const routes: Routes = [
  {path: '', component: UserListComponent},
  {
    path: ':id',
    component: UserComponent,
    children: [
      {path: 'todo', component: TodoListComponent},
      {path: 'todo/:todoId', component: TodoComponent},
      {path: 'friend', component: FriendListComponent},
      {path: 'friend/:friendId', component: FriendComponent},
    ],
  },
];
```
(this is part of `user-routing.module`, which is lazy loaded by `app-routing.module`)

I added a small util to the repo that you can trigger with `npm run gp`, it dumps out the results of Guess-Parser to the console:
```
┌─────────┬──────────────────────────┐
│ (index) │          Values          │
├─────────┼──────────────────────────┤
│    0    │         '/about'         │
│    1    │         '/home'          │
│    2    │         '/user'          │
│    3    │       '/user/todo'       │
│    4    │   '/user/todo/:todoId'   │
│    5    │      '/user/friend'      │
│    6    │ '/user/friend/:friendId' │
│    7    │       '/user/:id'        │
└─────────┴──────────────────────────┘
```
routes 3-6 are missing the users `id` in the path.
The app works as expected. see the below example:
![image](https://user-images.githubusercontent.com/1249083/73119499-1da6bc00-3f63-11ea-8f25-3aeeca919eaa.png)

**Comment by mgechev** [comment]
Thanks for reporting this! I'll check this out today.
