### ISSUE TITLE
guess-parser can't handle orphaned routes

### ISSUE THREAD

**Issue by SanderElias** [guess-js/guess#314]
In the same repo I created for #313 I commented out one of the lazy loaded routes like this:
```typescript
const routes: Routes = [
  // {
  //   path: "about",
  //   loadChildren: () => import("./about/about.module").then(m => m.AboutModule)
  // },
  {
    path: "home",
    loadChildren: () => import("./home/home.module").then(m => m.HomeModule)
  },
  {
    path: "user",
    loadChildren: () => import("./user/user.module").then(m => m.UserModule)
  }
];
```

Note, I didn't remove the actual about-module, but this is not loaded by my angular app anymore.
In Angular everything works as expected, except this module is no longer accessible.

now the `npm run gp` utility function gives the following error:
![image](https://user-images.githubusercontent.com/1249083/73121659-c0b7ff80-3f7c-11ea-9f4d-dd96d27ef60f.png)

Would it be possible to not error out on orphaned modules?

**Comment by mgechev** [comment]
I'm not able to reproduce this issue. After commenting the `about` route the `about.module.ts` is no longer part of the TypeScript program, so the parser does not have to process it.

**Comment by SanderElias** [comment]
It seems that we need to feed it the tsconfig.app.json, and not the containing folder. I will update that, and report back if there is still an issue.
