### ISSUE TITLE
Angular9 Unable to extract routes from application.

### ISSUE THREAD

**Issue by mustordont** [guess-js/guess#335]
1. Created new angular9 app
2. Added SSR:
> ng add @nguniversal/express-engine

3. Added lazy-load module:
> $ ng g m test --route test --module app

4. Moved routes from separate routing module to the main lazy-load module: [test.module.ts](https://github.com/mustordont/nguniversal-guess-routes/blob/master/src/app/test/test.module.ts)

5. Run:
> npm run prerender

guess-js throws: 
> Unable to extract routes from application.

Affects only Windows machines
Reproduction: https://github.com/mustordont/nguniversal-guess-routes

**Comment by mgechev** [comment]
Thanks for providing the repro! I'll try to look at it next week.

**Comment by kuncevic** [comment]
I had the same issue, prerender always throwing `Unable to extract routes from application` and I am on MAC, this error didn't happen like before RC.9 or something

**Comment by kuncevic** [comment]
I had the same issue, prerender always throwing `Unable to extract routes from application` 

![image](https://user-images.githubusercontent.com/1283734/74694197-40b34b80-5243-11ea-9cbf-122c318fef94.png)


This error started like after RC.8 or RC.9. However I've got my app prerendering with no issues though.

**Comment by c3mohamn** [comment]
Having the same issue. 

It's breaking in the mapping starting at line 535 in [angular/index.ts](https://github.com/guess-js/guess/blob/master/packages/guess-parser/src/angular/index.ts#L535
).

**Comment by mgechev** [comment]
@kuncevic, @c3mohamn can you provide a sample project where I can reproduce the issue?

**Comment by kuncevic** [comment]
Just migrated to v10 all seems good

**Comment by mgechev** [comment]
Closing for now. Free free to open a new issue if the problem is not resolved.
