### ISSUE TITLE
Angular: Any chance for routes dynamically put together?

### ISSUE THREAD

**Issue by cschwaderer** [guess-js/guess#349]
Since it is a requirement for my app, that all components need to be accessible from many different paths, I create my routes dynamically like so

```
var routesReady: Routes = [];

const routesPre = {
    "route1": {
        component: MyFirstComponent,
        paths: ["foo1","foo2","foo3" ... ]
    },
    "route2": {
        component: MySecondComponent,
        paths: ["bar1","bar2","bar3" ... ]
    }
}

for(let route in routesPre) {
    for(let i = 0; i < routesPre[route].paths.length; i++) {
        routesReady.push({
            path: routesPre[route].paths[i],
            component: routesPre[route].component
        });
    }
}
```
That works pretty well in Angular 9. In guess-api, however, it doesn't work at all.  Just an empty array is returned. If I change routesReady to `var routesReady: Routes = [{component: DummyComponent, path 'dummy/dummy'}];` then guess will at least return this route. So, there is no general problem with path to config or what not.

Is there any chance to get this to work? If I have absolutely no idea how guess tries to fetch the routes anyway and how I am supposed to define my routes in order to have them "guess-friendly". I couldn't find any documentation.

**Comment by mgechev** [comment]
The guess parser can't resolve the routes statically for such dynamic configurations. It's not possible to discover them at build time.
