### ISSUE TITLE
[guess-parser] Is not support Nextjs?

### ISSUE THREAD

**Issue by hideokamoto** [guess-js/guess#372]
## Expect behavior
- Configure guess.js configuration using by `guess-webpack` and `guess-parser`
- run `next build`
- guess.js works well

## Actual behavior
When we run `next build`, we'll get this error.

```
$ next build && next export
(node:57565) UnhandledPromiseRejectionWarning: Error: Cannot detect the application type
    at exports.parseRoutes (/Users/development/next-app/node_modules/guess-parser/dist/guess-parser/index.js:860:15)
```

## Issue
I've checked the code, I think the `guess-parser` does not support nextjs.

https://github.com/guess-js/guess/blob/3c55310899f601aeedfa483db571de905b6c8797/packages/guess-parser/src/detector/detect.ts

Is it possible to support Nextjs?

I think we need the following conditions, isn't it?

```typescript
  if (d('react') && d('next') {
    return { ...ANY_CONFIG };
  }
  if (d('react') && d('next') && exists('tsconfig.json')) {
    return { ...ANY_CONFIG };
  }
```

Thanks.

**Comment by mgechev** [comment]
You can find a demo with Next.js here https://github.com/mgechev/guess-next.

**Comment by hideokamoto** [comment]
I'm asking about `guess-parser`, not `guess-webpack`.
OK?

In `guess-parser`, the `detect.ts` files does not definition about next.js.
https://github.com/guess-js/guess/blob/3c55310899f601aeedfa483db571de905b6c8797/packages/guess-parser/src/detector/detect.ts
Only `Angular` `Create React App` `Gatsby` ` Preact`.

Is the `guess-parser` not for nextjs?

**Comment by hideokamoto** [comment]
Or, you mean we can not use `guess-parser` for nextjs?
I can't understand what you said.

**Comment by mgechev** [comment]
Yes, you are correct. The parser does not support Next.js which means that you can't take advantage of the ahead of time prefetching of Guess.js. At the same time, you can embed the prefetching instructions for your entire application as part of your main bundle. This way you can enable predictive prefetching for your Next.js app.

**Comment by hideokamoto** [comment]
I understand.
Thanks a lot.

**Comment by hideokamoto** [comment]
FYI.

My Next.js application config is here.
Probably, we can use GA information when we run `next build && next export`.

```
const { GuessPlugin } = require('guess-webpack');

module.exports = {
  webpack: function(config, { isServer }) {
    if (isServer) return config;
    if (process.env.NODE_ENV === 'development') return config;
    const jwtJSON = process.env.GA_JWT
    if (!jwtJSON) return config;
    const jwt = JSON.parse(jwtJSON)
    config.plugins.push(
      new GuessPlugin({
        debug: true,
        jwt,
        GA: process.env.GA_VIEW_ID
      })
    );
    return config;
  },
  exportTrailingSlash: true,
  exportPathMap: function() {
    return {
      '/': { page: '/' }
    };
  }
}

```
