### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by crisfranco15793** [guess-js/guess#408]
Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In.

This error occurs when I run ng build --prod

**Comment by mgechev** [comment]
Yes, that's currently a known issue https://github.com/guess-js/guess/issues/328.

My recommendation would be to use a JWT instead of OAuth. Closing this ticket since it's a duplicate.
