### ISSUE TITLE
[RFC] Guess function API

### ISSUE THREAD

**Issue by mgechev** [guess-js/guess#42]
## Prior art

Currently, `guess` has the following signature:

```ts
interface GuessFn {
  (route: string, links?: string[]): Predictions;
}

interface Predictions {
  [route: Route]: Probability;
}

type Route = string;
type Probability = number;
```

The call `guess(route)` returns an object literal which as keys has URLs/routes likely to be visited next, and values the associated probabilities.

If as a second argument we pass a list of URLs/routes the function will return an object with keys from the intersection between the passed data & the known possible navigations.

Few problems with this API is:

- `links: string[]` seem redundant. The consumer of `guess` can easily filter the links
- The returned result does not adapt based on the connection's effective type

## Proposal

I'm proposing the following API:

```ts
interface GuessFn {
  (params?: GuessFnParams): Predictions;
}

interface GuessFnParams {
  route?: Route;
  thresholds?: ConnectionEffectiveTypeThresholds;
  connection?: ConnectionEffectiveType;
}

type Route = string;
type Probability = number;
type ConnectionEffectiveType = '4g' | '3g' | '2g' | 'slow-2g';

interface ConnectionEffectiveTypeThresholds {
  '4g': Probability;
  '3g': Probability;
  '2g': Probability;
  'slow-2g': Probability;
}

interface Predictions {
  [route: Route]: Probability;
}
```

This way, `guess` could be invoked without any arguments (i.e. `guess()`). Such call will:

- Set `params.route` to `window.location.pathname` (since not specified)
- Use the build-time value for `params.thresholds` (since not specified)
- Use `window.navigator.connection.effectiveType` as value of `params.connection` (since not specified)
- `guess` will after that query the model and filter the results by the respective `connection` and `thresholds` values and return an object literal subtype of `Predictions`

Ideally, we'd want to have a method `prefetch()` which uses `guess()` internally and prefetches all the bundles associated with the returned routes. The problem here is that with this low-level API we don't have access to the route-bundle mapping. For Angular & React we resolve the mapping at build-time with `guess-parser`.

// cc @addyosmani @KyleAMathews

**Comment by addyosmani** [comment]
Thanks for putting together this proposal, @mgechev. Love this direction around setting better defaults for the connection and thresholds out of the box.  

Would it be possible to share a usage example with the updated interface?

> Ideally, we'd want to have a method prefetch() which uses guess() internally and prefetches all the bundles associated with the returned routes.

I'm wondering if we should open a separate issue to discuss a `prefetch()` method which wraps `guess()`. Would this have reduced boilerplate in the React or Angular integrations you worked on?

**Comment by mgechev** [comment]
With the new suggested API, a third-party plugin would be able to use Guess.js with additional runtime reduced to the minimum. The `GuessPlugin` will introduce only:

- `guess(...)` - function used for prediction
- The model (the Markov chain in this case)
- Two utility classes used for reading the model's compressed representation

This way we'll be able to get rid of:

1. The route change handler which tracks when the user navigates across pages
2. The prefetch polyfill because the plugin author can handle the prefetching using `guess(...)`

If we decide to go with `prefetch()` function, then we'll need to introduce 2.

We're still coupled to webpack because it introduces all this code as part of the main bundle. If we want to get independent form webpack the problem would be that we'll provide too low-level tools and everyone should figure out how to introduce the model as part of their bundle.

Here are few examples of the suggested API when we've used the `GuessPlugin` with the configuration:

```ts
new GuessPlugin({
  GA: GAViewID,
  runtime: {
    delegate: true,

   // Optional
    threshoulds: {
      '4g': 0.05,
      '3g': 0.08,
      '2g': 0.9,
      'slow-2g': 0.2
    }
  },
  routeProvider: false
})
```

...and the user has `navigator.connection.effectiveType` >= `2g`.

## Common scenario

Return the pages which are likely to be visited next from the current page:

```ts
guess();

/*
{
  "/a": 0.6,
  "/b": 0.3,
  "/c": 0.1
}
*/
```

## Request prediction for a different URL

If we want to get a prediction for a different page:

```ts
guess('/a');

/*
{
  "/b": 0.7,
  "/c": 0.1
}
*/
```

## Request prediction for a different URL

If we want to get a prediction for a different page:

```ts
guess({ route: '/a' });

/*
{
  "/b": 0.7,
  "/c": 0.1
}
*/
```

## Override defaults

If at runtime we want to change the thresholds:

```ts
const thresholds = {
  '4g': 0.05,
  '3g': 0.1,
  '2g': 0.3,
  'slow-2g': 0.5
};
const connection = 'slow-2g';

guess({ route: '/a', thresholds, connection });

/*
{
  "/b": 0.7
}
*/
```

**Comment by mgechev** [comment]
@KyleAMathews what do you think about this?

**Comment by KyleAMathews** [comment]
Looks great! It would be nice too if Guess exposed a util function for prefetching a URL as there's some decently complicated logic I remember around making prefetching work cross-browser that I don't want to duplicate in the Gatsby plugin.

**Comment by addyosmani** [comment]
I believe @mgechev and I may have had a discussion around preload-webpack-plugin in the context of this issue. I believe we'll want to circle back on this one and factor in what the right solution would be now that Webpack 4 also supports prefetch/preloading of chunks natively there.
