### ISSUE TITLE
Update @wessberg/ts-evaluator

### ISSUE THREAD

**Issue by ties-s** [guess-js/guess#425]
Can be @wessberg/ts-evaluator to the latest version? The current version doesn't support Typescrip 4.x so will produce these kinds of errors: `npm WARN @wessberg/ts-evaluator@0.0.26 requires a peer of typescript@^3.x but none is installed. You must install peer dependencies yourself.`

**Comment by mgechev** [comment]
Yes, I'll look into this today.

**Comment by mgechev** [comment]
It's out in 0.4.22.
