### ISSUE TITLE
[guess-parser] Return all routes of an Angular app

### ISSUE THREAD

**Issue by chrisguttandin** [guess-js/guess#44]
Hi @mgechev,

this is a follow up issue of [#1](https://github.com/mgechev/mlx/issues/1) of [@mlx/parser](https://github.com/mgechev/mlx). I guess `guess-parser` is the successor of `@mlx/parser`.

I can confirm, that parsing an Angular App which has a routing module generated by the CLI works now. However when there are nested routes `guess-parser` does not pick up those routes. I was abled to track down the problem. It seems to be problematic that the CLI does extract nested routes into their own modules as well but `guess-parser` expects them to be defined in the root module of any lazily loaded module.

Since explaining the problem is a bit difficult I created [a little example project](https://github.com/chrisguttandin/guess-parser-example). It is an app created by the Angular CLI. The README contains all the commands I used. It also contains a little script to invoke the `parseAngularRoutes()` function. It can be invoked by running `node parse.js`. I would expect it to return two routes (`zero` and `zero/first`) but it only returns the first.

Please let me know if you need more infos to reproduce the bug.

**Comment by addyosmani** [comment]
Thank you for filing an issue and creating a little reproduction project for us to check out, @chrisguttandin! That will be quite useful for debugging a solution for nested routes not being picked up. 

You're right that (afaik) we currently only parse routes out from the root module of lazily-loaded modules. I'll defer to @mgechev on how feasible it would be for us to extend `guess-parser` to also look at individual modules with nested routes. 

This is an interesting problem as we're likely to run into it more (with other frameworks too) once we determine the various different ways framework CLIs support developers customizing routes.

**Comment by mgechev** [comment]
@chrisguttandin thanks for providing a demo to reproduce the problem! Should be able to push a fix in a few hours.

**Comment by chrisguttandin** [comment]
Thanks @mgechev, I just made a test and can confirm that it works great now. I will go ahead and delete the example repo.

Would it be possible to publish the changes to npm?

**Comment by mgechev** [comment]
I need to sync with Gatsby because of some changes in the public API.

**Comment by chrisguttandin** [comment]
@mgechev Alright, thanks for the explanation.
