### ISSUE TITLE
Is there anny way/API to know which pages the user are going to be prefetched

### ISSUE THREAD

**Issue by MiltonAkash** [guess-js/guess#449]
Im using gatsbyJs. Is there way to know the predictions of links that are going to be prefetched so I can add extra stylings to them or display them in a separate place and make it easy for users to click

**Comment by mgechev** [comment]
You can find how we did that in the demo from Google I/O 2018 [here](https://github.com/guess-js/gatsby-guess/tree/master/plugins/gatsby-guess-js-link-highlight).
