### ISSUE TITLE
Gatsby plugin usage query (Getting a Webpack Error during build)

### ISSUE THREAD

**Issue by tsukhu** [guess-js/guess#47]
I am trying to get the gatsby plugin working in my project and during the build I get this error

WebpackError: ENOENT: no such file or directory, open '/home/travis/build/ERS-HCL/gatsby-demo-app/.cache/data.json

It would be great if you could let me know if I am missing something here

Here is the code change for including the gatsby plugin (on the same lines as your example) https://github.com/ERS-HCL/gatsby-demo-app/commit/43cadc9f0b1f6d2726fb485ab93429629465946f 

The travis build error is here https://travis-ci.org/ERS-HCL/gatsby-demo-app/builds/379160574

Thanks ,
Tarun

**Comment by addyosmani** [comment]
Paging @KyleAMathews in case he gets a chance to help debug the gatsby plugin issues above.

**Comment by KyleAMathews** [comment]
Hey, the guess gatsby plugin is for v2 only of gatsby as it uses some new APIs. Please try upgrading your site to v2 and give it another go! It might be easier to start with a v2 site from scratch as we still don't have an upgrade guide for v2 (coming soon). Check out the v2 branch on the official starters e.g. http://github.com/gatsbyjs/gatsby-starter-hello-world

**Comment by tsukhu** [comment]
@KyleAMathews thank you for the update. Just started reading about Gatsby v2 and will be keenly following it.
