### ISSUE TITLE
Allow use of constants in Angular Routes (Using Scully)

### ISSUE THREAD

**Issue by jamieking1996** [guess-js/guess#496]
Hi there, I raised on issue on the Scully gitter channel that it does not pre render child routes which are assigned to a constant. For example, when this child "privacy" route is in a constant like this:

```
const privacyState: Route = {
  path: 'privacy;,
  component: PrivacyComponent
}

export const rootState: Route = {
  path: '',
  component: AppComponent,
  children: [
    privacyState
  ]
}
```

However, it will pre render when the privacy route is hardcoded:

```
export const rootState: Route = {
  path: '',
  component: AppComponent,
  children: [
   {
      path: 'privacy;,
      component: PrivacyComponent
   }
  ]
}
```
Someone at the Scully team pointed out that Scully uses guess-parser for working out what routes can be pre rendered. He mentioned also that he has discussed this issue before with you, and the reason why you don't allow this was because it would take too long.

I am wondering if this could be supported through a configuration option? I can only speak for myself on this but I don't think I would mind waiting an extra period of time for Guess-Parser to work out child routes in variables. Of course I am thinking this "extra period" of time is in minutes. If it's anything longer, then I understand the decision to not do this.

Thanks in advance!

**Comment by mgechev** [comment]
The Guess.js parser does not support this construct, unfortunately. I'd consider this feature request outside the scope of the project.
