### ISSUE TITLE
Microsite 📃

### ISSUE THREAD

**Issue by addyosmani** [guess-js/guess#51]
Now that we have guessjs.com, we might want to put together a microsite for the project 🤔

@mgechev and I like the idea of using Gatsby as our static site framework. Given we already have a reference implementation of using Guess.js with it thanks to @KyleAMathews, this seems like a reasonable direction? What do folks think?

Some things to discuss regardless of stack:
-  Goals of the site 
-  Information architecture 
-  How we present the bundling vs non-bundling solutions (building on @khempenius's work in README)
-  Having a clear/easy getting started experience 
-  Keeping it easy to edit/contribute 

Once we're further along with the direction, I'm happy to try finding an owner to work on the site.

**Comment by mgechev** [comment]
Here it is https://guess-js.github.io/
