### ISSUE TITLE
TS2307: Cannot find module '@wessberg/ts-evaluator' or its corresponding type declarations.

### ISSUE THREAD

**Issue by RA80533** [guess-js/guess#512]
~~Running `npm run build` results in the error being emitted during Webpack compilation. \@wessberg/ts-evaluator is used in guess-parser but is not declared as a dependency anywhere in the project.~~

~~While both guess-ga and guess-webpack are structured in a manner that takes advantage of Lerna's workspace functionality, guess-parser is simply an extension of the project defined at the root directory of the repository. Its dependencies are sourced—intentionally or not—from those of the would-be parent project in the monorepo. In other words, an immediate fix would be to add \@wessberg/ts-evaluator as an immediate dependency of the guess package.~~

```
ERROR in /[…]/guess/packages/guess-parser/src/angular/routes.ts
./src/angular/routes.ts
[tsl] ERROR in /[…]/guess/packages/guess-parser/src/angular/routes.ts(2,26)
      TS2307: Cannot find module '@wessberg/ts-evaluator' or its corresponding type declarations.
```

EDIT: It appears that ts-evaluator is the non-deprecated version of \@wessberg/ts-evaluator. The imports of the latter should be updated to correspond with the change.

**Comment by mgarcos** [comment]
When will this be released?
