### ISSUE TITLE
[Docs] Type of sites we are targeting

### ISSUE THREAD

**Issue by addyosmani** [guess-js/guess#56]
A common question I get is what size/scale of site Guess.js is targeting. I think it's worth documenting this a little more clearly. My two cents:

* Sites with nested pages (e.g have a minimum of three levels of nesting). Good examples: news and publisher sites, e-commerce, large SaaS sites)
* Sites who have already been using Analytics tracking for a while (likely to have a rich set of data that can be used for predictive fetching).

**Comment by addyosmani** [comment]
Another question we might want to document an answer to is if sites with less than say, 10 views benefit from this approach at all. Speaking to one site, they noted they currently precache the other 9 views when the first view is being loaded and feel prefetching intelligently isn't needed there which is fair.

I see larger sites finding this useful. In particular for data fetching. I believe this is what @kylemathews did for the Wikipedia example and this site did point out smarter data prefetching would be valuable to them.

**Comment by rockeynebhwani** [comment]
@addyosmani  - We tried to use this for a large eCommerce site with this configuration and this configuration (which takes the report for one day) results in a report which is about 100000 lines. However, it is still too big for the plugin and it hits one of the quotas for the maximum amount of service calls.

new GuessPlugin(
  {
    GA:'XXXXXXXX',
    period:{
      startDate:newDate('2019-1-15'),
      endDate:newDate('2019-1-16')
    }
  }
)

I am not aware of any other configuration which can be added to further reduce this set. So we want to understand if this is really usable in current shape for big eCommerce sites with large volumes? Thoughts?

**Comment by mgechev** [comment]
@rockeynebhwani I'm talking to the Google Analytics team, so we can hopefully come up with a solution.

**Comment by rockeynebhwani** [comment]
Thanks @mgechev for your response.. We are trying to use guess.js with React / Webpack. As you can see, we have already reduce the time range to 1 day. Can I go lower than this ? Looking at config 'startDate' and 'endDate',  it looks like we can only provide dates and can't go lower than this... 

I am struggling to find a link to request increase in quota limit. This is for an enterprise site where GA account is set up by an agency.. so I am not sure if it's I am authorized to request increase in quota...  I also liked idea from @addyosmani to point to a URL for requesting bump in quota - https://github.com/guess-js/guess/issues/67

**Comment by sammydigits** [comment]
Info on increasing the GA Reporting API quota can be found here:

https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas
