### ISSUE TITLE
SPFJS - GUESS

### ISSUE THREAD

**Issue by romulocintra** [guess-js/guess#64]
Hi @addyosmani  @mgechev  , this is a little unrelated topic ... but i was building some micro front end services kind of framework that fetch content and render to page as fragments etc ... 

I saw  SPF-js from google and found very futuristic for that time and is great and i see guess-js doing similar thing in another level - but they share some similar goals --- one of them is prefetch content to improve experience for user . 

But today with SW and all browser capabilities , what do you recommend for an architecture similar to SPF-JS sites .

Big web application that needs to render fragments from different teams in same page , if possible all SSRendered . being independent sharing routing from server to client. 

I know is kind of silly question but was the unique place i can sit down both of the you.

**Comment by mgechev** [comment]
Hey @romulocintra, I'll close this issue because it doesn't seem related to Guess.js. We can continue the discussion in another channel.

**Comment by romulocintra** [comment]
@mgechev  thanks and yeah , is not related ... Thanks  :)
