### ISSUE TITLE
Cannot build with guess api

### ISSUE THREAD

**Issue by dijs** [guess-js/guess#65]
When using:
```js
  runtime: {
    delegate: true
  }
```

and 

`import { guess } from 'guess-webpack/api'`

Webpack is throwing this:

```
Module not found: Error: Can't resolve 'guess-webpack/api' in '...'
```

Any ideas?

**Comment by mgechev** [comment]
Thanks for giving Guess.js a try! Would you share a minimal demo where we can reproduce the problem?

**Comment by mgechev** [comment]
@dijs I found the cause. Will push a fix in the next a couple of hours.

**Comment by mgechev** [comment]
@dijs now `guess-webpack/api` is in the right place in v0.1.4 🚢 ! Thanks for reporting the issue and excuse me for the inconvenience!
