### ISSUE TITLE
Feature Request/Enhancement: Use tabable instead of old compiler API for webpack-plugin

### ISSUE THREAD

**Issue by evenstensberg** [guess-js/guess#72]
Hi! When running GuessJS I'm getting a warning that says that the old interface is depreciated. It would be nice if GuessJS uses the new webpack plugin API with tapable instead.

**Comment by mgechev** [comment]
Hey @ev1stensberg, thanks for the suggestion!

Currently, by using the deprecated API, we maintain support for both webpack 3 and webpack 4 with minimal abstractions. The main reason for us supporting webpack 3 is compatibility with Angular CLI < v6.

Now given the current status of Angular CLI v6, we'll consider moving from the deprecated API shortly.

**Comment by mgechev** [comment]
We can already move away from webpack 3. If anyone is willing to help, feel free to take this issue.

**Comment by mgechev** [comment]
https://github.com/guess-js/guess/commit/7f8282b1786d0adc741c59b55d4fcf92bdd034c5 this should do it.
