### ISSUE TITLE
TypeError: ts.createNodeArray is not a function

### ISSUE THREAD

**Issue by KyleAMathews** [guess-js/guess#76]
I just tried adding gatsby-plugin-guess-js to gatsbyjs.org and hit the above error.

Looks like it's part of the code for Angular?

**Comment by mgechev** [comment]
I'll look at this tomorrow/Wednesday and follow up with you.

**Comment by mgechev** [comment]
This worked for me. Here are the changes I did:

<img width="385" alt="screen shot 2018-09-04 at 19 10 01" src="https://user-images.githubusercontent.com/455023/45067065-3d8bc600-b076-11e8-9239-41d98274eca5.png">

**Comment by mgechev** [comment]
@KyleAMathews do you have any updates? Are you still hitting the issue?

**Comment by centrical** [comment]
I do. I installed it, and when I try to spin up the dev environment it fails. The error message speaks of "Angular", which is really weird. 

error Plugin gatsby-plugin-guess-js returned an error

  TypeError: ts.createNodeArray is not a function
  
  - evaluator.js:661 Object.<anonymous>
    [unless.com]/[@angular]/compiler-cli/src/metadata/evaluator.js:661:16

**Comment by mgechev** [comment]
Thanks for the comment, @centrical. In the next version of Guess.js we'll externalize the parsers which should fix this issue.

**Comment by mgechev** [comment]
@centrical would you try `guess-webpack@0.1.6`?
