### ISSUE TITLE
Cannot read property 'guess' of undefined

### ISSUE THREAD

**Issue by ctf0** [guess-js/guess#83]
am trying to use guess with laravel through a pre-defined routes file like in [nuxt example](https://guess-js.github.io/docs/nuxt) so the setup is 

- `guess-routes.json` ex.
```json
{
    "\/": {
        "\/login": 2,
        "\/about": 1
    },
    "\/about": {
        "\/contact-us": 1
    },
    "\/contact-us": {
        "\/": 1
    }
}
```

- webpack
```js
const {readFileSync} = require('fs')
const {GuessPlugin} = require('guess-webpack')

mix.webpackConfig({
    plugins: [
        new GuessPlugin({
            reportProvider() {
                return Promise.resolve(JSON.parse(readFileSync('./guess-routes.json')))
            }
        })
    ]
})
```

- app.js
```js
import {guess} from 'guess-webpack/api'
guess()
```

- error
![demo](https://user-images.githubusercontent.com/7388088/47900590-15f28780-de86-11e8-80fe-56d055974712.jpg)

**Comment by daliborgogic** [comment]
@mgechev Yes. `guess` runs only on client side. In webpack config just add condition @ctf0

**Comment by ctf0** [comment]
@daliborgogic can u elaborate ? an example might help as well

**Comment by daliborgogic** [comment]
@ctf0 Of course.
In [nuxt.js](https://github.com/nuxt/nuxt.js) we have way to check environment `isServer` or it's for a  client `isClient`  during the build/

```javascript
// nuxt.config.js
import { readFileSync } from 'fs'
import { GuessPlugin } from 'guess-webpack'

export default {
  build: {
    extend(config, ctx) {
      if (ctx.isClient) {
        config.plugins.push(
          new GuessPlugin({
            reportProvider() {
              return Promise.resolve(JSON.parse(readFileSync('./routes.json')))
            }
          })
        )
      }
    }
  }
}
```

If you don't have option to check environment during the build (laravel):

```javascript
// webpack
const { readFileSync } = require('fs')
const { GuessPlugin } = require('guess-webpack')

mix.webpackConfig({
  plugins: [
    new webpack.DefinePlugin({
      APP_ENV: JSON.stringify('browser')
    }),
    if (process.env.APP_ENV === 'browser') {
      new GuessPlugin({
        reportProvider() {
          return Promise.resolve(JSON.parse(readFileSync('./guess-routes.json')))
        }
      })
    ]
  }
})
```

Let us know if this approach works for you, and `GuessPlugin` runs only on client side

**Comment by daliborgogic** [comment]
I think real problem is in `app.js`.
This is required because we don't want to run Guess.js on the server
```javascript
if (typeof window !== 'undefined') {
   // Invoke guess() here
}
```

**Comment by mgechev** [comment]
Would you share a minimum demo where we can reproduce the problem?

**Comment by ctf0** [comment]
sure, here is a repo https://github.com/ctf0/guess-demo/tree/master it requires having `laravel & composer` installed on ur system

**Comment by zipme** [comment]
I have the same issue here with a nuxt project, I am using this module https://github.com/nuxt-community/guess-module

The config in nuxt.config.js is something like: 
```js
['@nuxtjs/guess', {
  GA: process.env.GA_VIEW_ID,
  jwt: {
    private_key: process.env.GA_PRIVATE_KEY,
    client_email: process.env.GA_CLIENT_EMAIL
  },
  period: {
    startDate: new Date('2018-09-01'),
    endDate: new Date('2018-10-09')
  },
  runtime: {
    delegate: true,
    prefetchConfig: {
      '4g': 0.3,
      '3g': 0.3,
      '2g': 0.3,
      'slow-2g': 0.3
    }
  }
}],
```

**Comment by daliborgogic** [comment]
@zipme `guess-webpack` don't have option `jwt`. Can you share your `nuxt.config.js`?

**Comment by zipme** [comment]
@daliborgogic  Hi, I think it does, check this thread https://github.com/guess-js/guess/issues/80

**Comment by daliborgogic** [comment]
Thanks for point to this thread. Will check if there is any changes in API.

**Comment by daliborgogic** [comment]
@zipme Is your `GA` in format `UA-XXXXXXXX-X` or `XXXXXXXX`?

**Comment by zipme** [comment]
it's the view id, it's XXXXXXXX

**Comment by zipme** [comment]
hi @daliborgogic , after I disabled the pwa and remove all the cache the error seems to be gone, I guess it was the previous cached js caused the issue. Thanks for the help!!

**Comment by mgechev** [comment]
How did you disabled the PWA? Ideally, Guess.js should not interfer with other modules.

**Comment by zipme** [comment]
@mgechev I guess the issue I have is that I did some misconfiguration in the nuxt.config, but because of the PWA, the incorrect js file was being loaded even though I adjusted the config file, after I temporarily disabled the pwa module and clear the cache it works.

**Comment by ctf0** [comment]
@mgechev any news :balloon:  ?
