### ISSUE TITLE
Demo breaked

### ISSUE THREAD

**Issue by bertho-zero** [guess-js/guess#87]
Visible in the console from https://guess-static-sites-demo.firebaseapp.com/

```
Access to XMLHttpRequest at 'https://guess-static-sites-demo.appspot.com/' from origin 'https://guess-static-sites-demo.firebaseapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by mgechev** [comment]
@khempenius do you know what might be happening here?

**Comment by bertho-zero** [comment]
The first line of https://guess-static-sites-demo.firebaseapp.com/predictiveFetching.js is bad:

```js
const ENDPOINT = 'https://guess-static-sites-demo.appspot.com/'
```

**Comment by khempenius** [comment]
That line is not the issue (the API and front-end are served from different domains).

That repo and database were on my laptop that died. I'm going to briefly take down the demo link while I recreate them.
